---
- name: set docker_exec_cmd fact
  set_fact:
    docker_exec_cmd: "docker exec ceph-mds-{{ ansible_hostname }}"

- include: copy_configs.yml
- include: start_docker_mds.yml

- include: debug_docker_mds.yml
  when:
    - mds_socket.rc != 0

- include: enable_multimds.yml
