---
- include: pre_requisite.yml
  when: not containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- include: openstack-keystone.yml
  when:
    - radosgw_keystone|bool
    - radosgw_keystone_ssl|bool
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- name: include rgw_pool_pgs.yml
  include: rgw_pool_pgs.yml
  when: create_pools is defined
  static: False

- include: start_radosgw.yml
  when: not containerized_deployment
  static: False

- name: include rgw multisite playbooks
  include: multisite/main.yml
  when:
    - rgw_multisite
    - ( ceph_release_num.{{ ceph_release }} >= ceph_release_num.jewel )
  static: False

- name: include rgw_compression.yml
  include: rgw_compression.yml
  when: 
    - rgw_compression_type != 'None'
  static: False

- include: ./docker/main.yml
  when: containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False
